using System.Collections.Generic;
using CommandLine;
using CommandLine.Text;

namespace COMBinator
{
    class Options
    {
        // automatic / semi-automatic parameter

        [Option("auto633", HelpText = "Assume 633 nm CCL component.")]
        public bool Auto633 { get; set; }

        [Option('t', "target", DefaultValue = null, HelpText = "Target frequency in Hz.")]
        public double? TargetFrequency { get; set; }

        // options to set filter parameters

        [Option("nofilter", HelpText = "Suppress outlier checking.")]
        public bool NoFilter { get; set; }

        [Option("frep_set", DefaultValue = null, HelpText = "f_rep-IF in Hz.")]
        public double? FrepSetpoint { get; set; }

        [Option("frep_tol", DefaultValue = 0.010, HelpText = "Tolerance for f_rep-IF in Hz.")]
        public double FrepTolerance { get; set; }

        [Option("foff_tol", DefaultValue = 20, HelpText = "Tolerance for f_off in Hz.")]
        public double FoffTolerance { get; set; }

        [Option("cyc_tol", DefaultValue = 1.0, HelpText = "Tolerance for cycle slip detection in Hz")]
        public double CycTolerance { get; set; }

        // options for manual calculation

        [Option('m', "mode", DefaultValue = 0, HelpText = "Mode number.")]
        public int ModeNumber { get; set; }

        [Option("pb", HelpText = "Positive beat.")]
        public bool Bpb { get; set; }

        [Option("nb", HelpText = "Negative beat.")]
        public bool Bnb { get; set; }

        [Option("po", HelpText = "Positive offset.")]
        public bool Bpo { get; set; }

        [Option("no", HelpText = "Negative offset.")]
        public bool Bno { get; set; }

        [Option("MJD", HelpText = "Plotfile uses MJD.")]
        public bool Mjd { get; set; }

        // common user interface options

        [Option('q', "quiet", HelpText = "Quiet mode. No screen output (except for errors).")]
        public bool Quiet { get; set; }

        [Option("noheader", HelpText = "Suppress header in outfile.")]
        public bool NoHeader { get; set; }

        [Option("noaux", HelpText = "Suppress generation of plotfile.")]
        public bool NoAuxFile { get; set; }

        [Option("comb", DefaultValue = 1, HelpText = "Comb type (see doc).")]
        public int CombTypeNumber { get; set; }

        [Option("comment", DefaultValue = "", HelpText = "User supplied comment.")]
        public string Comment { get; set; }

        [Option("FXM", DefaultValue = 1, HelpText = "FXM counter to be used (1 or 2).")]
        public int FxmNumber { get; set; }


        [ValueList(typeof(List<string>), MaximumElements = 3)]
        public IList<string> ListOfFileNames { get; set; }

        [HelpOption]
        public string GetUsage()
        {
            string AppName = System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            string AppVer = System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString();

            HelpText help = new HelpText
            {
                Heading = new HeadingInfo(AppName, "version " + AppVer),
                Copyright = new CopyrightInfo("Michael Matus", 2021),
                AdditionalNewLineAfterOption = false,
                AddDashesToOption = true
            };

            string sPre1 = "Converts data files generated by MENLO femtosecond combs " +
                            "into a more user friendly format. Furthermore it performs " +
                            "some basic checking (optional) of the data and calculates " +
                            "the laser frequency to be calibrated. It is primarly intended to " +
                            "be used in conjunction with the BEV fibre combs and " +
                            "thus can not handle some of the older data files generated " +
                            "by the TiSa comb setup.";

            string sPre2 = "Up to 8 frequency and 2 voltages can make up a single " +
                            "data sample of the input files. The meaning of the channels " +
                            "is quite specific. The frequency values of a single comb " +
                            "can be in channels 1 - 4 or 5 - 8 (or both, each group " +
                            "representing a FXM counter), the remaining values are the voltage readings.";


            help.AddPreOptionsLine(" ");
            help.AddPreOptionsLine(sPre1);
            help.AddPreOptionsLine("");
            help.AddPreOptionsLine("Hardware specific topics:");
            help.AddPreOptionsLine(sPre2);
            help.AddPreOptionsLine("");
            help.AddPreOptionsLine("Usage: " + AppName + " filename1 [filename2 [filename3]] [options]");
            help.AddPostOptionsLine("Meaning of comb type number:");
            help.AddPostOptionsLine("  1: BEV FC1500-0-053 fiber comb, frequency doubled output");
            help.AddPostOptionsLine("  2: BEV FC1500-0-053 fiber comb, fundamental output");
            help.AddPostOptionsLine("  3: BEV FC8003/01 Ti:Sa comb");
            help.AddPostOptionsLine("  4: CMI FC8004 Ti:Sa comb");
            help.AddPostOptionsLine("  5: BEV FC1500-250-ULN fiber comb, fundamental output");
            help.AddPostOptionsLine("  6: BEV FC1500-250-ULN fiber comb, frequency doubled output");
            help.AddPostOptionsLine("  other: generic comb");
            help.AddPostOptionsLine("");

            help.AddOptions(this);

            return help;

        }
    }

}
